
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Acer
 */
public class CD_EmpExit extends javax.swing.JFrame {

    /**
     * Creates new form checkOut1
     */
    public CD_EmpExit() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground( Color.decode("#292929"));
    }

    static long find(String join_date, String leave_date) {
        // Create an instance of the SimpleDateFormat class  
        SimpleDateFormat obj = new SimpleDateFormat("MM-dd-yyyy HH:mm:ss");
        long time_difference = 0l;
        // In the try block, we will try to find the difference  
        try {
            // Use parse method to get date object of both dates  
            Date date1 = obj.parse(join_date);
            Date date2 = obj.parse(leave_date);
            // Calucalte time difference in milliseconds   
            time_difference = date2.getTime() - date1.getTime();

        } // Catch parse exception   
        catch (ParseException excep) {
            excep.printStackTrace();
        }
        return time_difference;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public String na;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NUMBER = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        L1 = new javax.swing.JTextField();
        L2 = new javax.swing.JTextField();
        L3 = new javax.swing.JTextField();
        L4 = new javax.swing.JTextField();
        L5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BILL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, -1, -1));

        NUMBER.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        NUMBER.setForeground(new java.awt.Color(255, 255, 255));
        NUMBER.setText("Enter Vehicle Number");
        getContentPane().add(NUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 330, 36));

        tf1.setBackground(new java.awt.Color(96, 96, 96));
        tf1.setFont(new java.awt.Font("Poppins", 0, 27)); // NOI18N
        tf1.setForeground(new java.awt.Color(255, 255, 255));
        tf1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 430, -1));

        jButton1.setBackground(new java.awt.Color(31, 31, 31));
        jButton1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GET BILL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 860, 220, 60));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vehicle Number :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, 40));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Check out : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 731, 270, 40));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check in :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 250, 40));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Time :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Amount :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 650, 250, 40));

        jButton2.setBackground(new java.awt.Color(31, 31, 31));
        jButton2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 860, 220, 60));

        L1.setEditable(false);
        L1.setBackground(new java.awt.Color(96, 96, 96));
        L1.setFont(new java.awt.Font("Poppins", 0, 27)); // NOI18N
        L1.setForeground(new java.awt.Color(255, 255, 255));
        L1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 420, 326, 40));

        L2.setEditable(false);
        L2.setBackground(new java.awt.Color(96, 96, 96));
        L2.setFont(new java.awt.Font("Poppins", 0, 27)); // NOI18N
        L2.setForeground(new java.awt.Color(255, 255, 255));
        L2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, 326, 40));

        L3.setEditable(false);
        L3.setBackground(new java.awt.Color(96, 96, 96));
        L3.setFont(new java.awt.Font("Poppins", 0, 27)); // NOI18N
        L3.setForeground(new java.awt.Color(255, 255, 255));
        L3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 730, 326, 40));

        L4.setEditable(false);
        L4.setBackground(new java.awt.Color(96, 96, 96));
        L4.setFont(new java.awt.Font("Poppins", 0, 27)); // NOI18N
        L4.setForeground(new java.awt.Color(255, 255, 255));
        L4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 570, 326, 40));

        L5.setEditable(false);
        L5.setBackground(new java.awt.Color(96, 96, 96));
        L5.setFont(new java.awt.Font("Poppins", 0, 27)); // NOI18N
        L5.setForeground(new java.awt.Color(255, 255, 255));
        L5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 650, 326, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("MM-dd-yyyy HH:mm:ss");
        String outtime = myDateObj.format(myFormatObj);
        Connection con = null;
        double amount;

        ResultSet r = null;
        String a = tf1.getText();

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kaus?autoReconnect=true&useSSL=false","root","root");
            String sql = "SELECT in_time from  customer where v_no=?";
            String sql1 = "update   customer set out_time=? where v_no=?";
            String sql2 = "update   customer set status=?,type_v=?,pay_am=? where v_no=?";
            PreparedStatement s = con.prepareStatement(sql);
            PreparedStatement s1 = con.prepareStatement(sql1);
            PreparedStatement s2 = con.prepareStatement(sql2);
            s.setString(1, a);
            s1.setString(1, outtime);
            s1.setString(2, a);
            r = s.executeQuery();
            s1.executeUpdate();
            if (r.next()) {
                na = r.getString("in_time");
                s2.setString(1, "paid");
                s2.setString(2, null);
                s2.setString(4, a);
                

                double d = ((double) find(na, outtime) / (1000 * 60 * 60));
                L4.setText(Double.toString(d));

                if (d <= 2) {
                    amount = 50;
                } else {
                    amount = (50 + (d - 2) * 21);
                }
                s2.setString(3,Double.toString(amount));
                s2.executeUpdate();

            } else {
                JOptionPane.showMessageDialog(this, "PLEASE ENTER VALID VEHICLE NUMBER");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CD_EmpExit.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException e) {
            System.out.println(e.getMessage());

        }
        
                        if (na.equalsIgnoreCase(null)) {
                } else {
                    L1.setText(a);
                    L2.setText(na);
                    L3.setText(outtime);

                }

        double d = ((double) find(na, outtime) / (1000 * 60 * 60));
        L4.setText(Double.toString(d));

        if (d <= 2) {
            amount = 50;
        } else {
            amount = (50 + (d - 2) * 21);
        }
        L5.setText(Double.toString(amount));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new CA_EmpHome().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CD_EmpExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CD_EmpExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CD_EmpExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CD_EmpExit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CD_EmpExit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField L1;
    private javax.swing.JTextField L2;
    private javax.swing.JTextField L3;
    private javax.swing.JTextField L4;
    private javax.swing.JTextField L5;
    private javax.swing.JLabel NUMBER;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
